export { IniDataRegistry } from './registry.js';
export { DEFAULT_AI_CONFIG } from './registry.js';
export type {
  AiConfig,
  ObjectDef,
  WeaponDef,
  ArmorDef,
  UpgradeDef,
  ScienceDef,
  FactionDef,
  LocomotorDef,
  AudioEventDef,
  AudioEventSoundType,
  MiscAudioDef,
  MusicTracksByType,
  MappedImageDef,
  ObjectCreationListDef,
  CommandButtonDef,
  CommandSetButtonSlot,
  CommandSetDef,
  SpecialPowerDef,
  RawBlockDef,
  RegistryStats,
  RegistryError,
  AudioSettingsConfig,
  GameDataConfig,
  VertexWaterSetting,
  WeaponBonusEntry,
  IniDataBundle,
} from './registry.js';
